#!/usr/bin/env python
from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TITANIUM_API_EXPORT', 1))

sources = Glob('*.cpp')
if build.is_osx():
	env.Append(FRAMEWORKS = ['Cocoa'])
	sources.extend(Glob('osx/*.cpp'))
	sources.extend(Glob('osx/*.mm'))

if build.is_linux():
	sources.extend(Glob('gst/*.cpp'))
	env.ParseConfig('pkg-config --cflags --libs gstreamer-0.10 gdk-2.0')

elif build.is_win32():
	build.add_thirdparty(env, 'microsoft')
	sources.extend(Glob('win32/*.cpp'))
	env.Append(LIBS=['user32', 'strmiids', 'ole32', 'oleaut32'])

build.mark_build_target(env.SharedLibrary(
	path.join(module.dir, 'timediamodule'), sources))

