#!/usr/bin/env python
from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TITANIUM_FILESYSTEM_API_EXPORT', 1))

if build.is_osx():
	env.Append(FRAMEWORKS = ['Cocoa'])

if build.is_win32():
	env.Append(LIBS=['shell32', 'user32', 'comdlg32', 'ole32'])

# Copy support files into module build directory
build.mark_build_target(build.utils.CopyTree(Glob('support/*'), module.dir))

build.mark_build_target(env.SharedLibrary(
	path.join(module.dir, 'tifilesystemmodule'), Glob('*.cpp')))
