#!/usr/bin/env python
from os import path
Import('build env module')

env.Append(CPPDEFINES = ('TITANIUM_PLATFORM_API_EXPORT', 1))

if build.is_win32():
	env.Append(LIBS=['shell32'])

elif build.is_osx():
	env.Append(FRAMEWORKS = ['AppKit', 'Cocoa'])

elif build.is_linux():
	env.ParseConfig('pkg-config --cflags --libs gdk-2.0 x11')

sources = [File('platform_module.cpp'), File('platform_binding.cpp')]
if build.is_osx():
	sources.append(File('platform_binding_%s.mm' % build.os))
else:
	sources.append(File('platform_binding_%s.cpp' % build.os))

build.mark_build_target(env.SharedLibrary(
	path.join(module.dir, 'tiplatformmodule'), sources))
